matrix:
  include:
    - DOCKER_RUBY_VERSION: 1.9.3
      RUBY_IMAGE_TAG: 1.9.3

    - DOCKER_RUBY_VERSION: 2.2
      RUBY_IMAGE_TAG: 2.2

build:
  image: abakpress/dind
  pull: true
  privileged: true
  volumes:
    - /home/data/drone/images:/images
    - /home/data/drone/gems:/bundle
    - /home/data/drone/key_cache:/ssh_keys
  environment:
    - COMPOSE_FILE_EXT=drone
    - POSTGRES_IMAGE_TAG=9.3
  commands:
    - wrapdocker docker -v

    - fetch-images
      --image whilp/ssh-agent
      --image abakpress/ruby:$RUBY_IMAGE_TAG
      --image abakpress/postgres:$POSTGRES_IMAGE_TAG

    - dip ssh add -T -v /ssh_keys -k /ssh_keys/id_rsa
    - dip provision
    - dip rspec
