name: build

kind: pipeline
type: docker

volumes:
- name: images
  host:
    path: /home/data/drone/images
- name: bundle
  host:
    path: /home/data/drone/gems
- name: keys
  host:
    path: /home/data/drone/key_cache

spec_step_common: &spec_step_common
  image: abakpress/dind-testing
  pull: always
  privileged: true
  volumes:
  - name: images
    path: /images
  - name: bundle
    path: /bundle
  - name: keys
    path: /ssh_keys
  commands:
  - prepare-build

  - fetch-images
    --image whilp/ssh-agent
    --image abakpress/ruby-app:$RUBY_IMAGE_TAG

  - dip ssh add -T -v /ssh_keys -k /ssh_keys/id_rsa
  - dip provision
  - dip rspec

steps:
- name: Tests Ruby 2.5
  environment:
    COMPOSE_FILE_EXT: drone
    DOCKER_RUBY_VERSION: 2.5
    RUBY_IMAGE_TAG: 2.5-latest
    RAILS_ENV: test
    BUNDLER_OPTIONS: " --without 'development production profile console assets' -j 10 --quiet"
    BUNDLER_VERSION: 1.17.3
  <<: *spec_step_common

- name: release
  image: abakpress/gem-publication:latest
  pull: true
  when:
    event: push
    branch: master
    status: success
  commands:
  - release-gem --public