---
kind: pipeline
type: docker
name: build

volumes:
  - name: rubygems
    host:
      path: /home/data/drone/rubygems
  - name: bundle
    host:
      path: /home/data/drone/gems

spec_step_common: &spec_step_common
  pull: if-not-exists
  volumes:
  - name: bundle
    path: /bundle
  commands:
  - rm -fr Gemfile.lock gemfiles/
  - bundle install -j 5
  - bundle exec appraisal install
  - bundle exec appraisal bundle exec rspec

steps:
- name: postgres
  image: abakpress/postgres-db:9.6-latest
  pull: if-not-exists
  environment:
    POSTGRES_DB: docker
  detach: true

- name: build on ruby2.3
  image: abakpress/ruby-app:2.3-latest
  environment:
    TEST_DB_HOST: postgres
    TEST_DB_NAME: docker
    TEST_DB_USERNAME: postgres
    BUNDLE_PATH: /bundle/2.3
  <<: *spec_step_common

- name: build on ruby2.4
  image: abakpress/ruby-app:2.4-latest
  environment:
    TEST_DB_HOST: postgres
    TEST_DB_NAME: docker
    TEST_DB_USERNAME: postgres
    BUNDLE_PATH: /bundle/2.4
  <<: *spec_step_common

- name: release
  image: abakpress/gem-publication:latest
  pull: if-not-exists
  when:
    event: push
    branch: master
    status: success
  volumes:
  - name: rubygems
    path: /root/.gem
  commands:
    - release-gem --public

